### ISSUE TITLE
Unable to open nested Record selector for self-referential FK

### ISSUE THREAD

**Issue by seancolsen** [centerofci/mathesar#3290]
## Steps to reproduce

1. Load the [all_types](https://github.com/centerofci/mathesar-data-playground/blob/master/all_data_types/all_data_types.sql) through psql and reflect changes.
1. Open the record selector on the `all_types` table
1. Try to open the nested record selector for the `fk` column
1. Expect to see a nested record selector
1. Instead observe the nested selector to open momentarily and begin loading but then to close

https://github.com/centerofci/mathesar/assets/42411/9a13f3df-c3b9-444f-8626-bef6487199e6

**Comment by FidalMathew** [comment]
@seancolsen can I work on this issue?

**Comment by seancolsen** [comment]
Sure @FidalMathew go ahead

**Comment by alanouda2** [comment]
@seancolsen We are a group of students currently working on open-source projects, we would love to be assigned this issue to fix it as soon as possible.

**Comment by Tweniee** [comment]
@seancolsen please have a look. when i am uploading [all_types](https://github.com/centerofci/mathesar-data-playground/blob/master/all_data_types/all_data_types.sql) its saying `Unable to tabulate data`
![Screenshot from 2023-11-17 17-46-54](https://github.com/centerofci/mathesar/assets/93429474/d16e664e-7cb4-41df-b913-69cf55762cd9)

![Screenshot from 2023-11-17 17-49-18](https://github.com/centerofci/mathesar/assets/93429474/285271b1-865b-4325-8f38-7d5b52343147)

**Comment by Tweniee** [comment]
Am i missing something, please do help me out. thanks

**Comment by seancolsen** [comment]
@FidalMathew I've unassigned you from this issue due to inactivity. You're still welcome to work on it and submit a PR.

**Comment by seancolsen** [comment]
@alanouda2 You're welcome to work on this and submit a PR, but in general we don't assign tickets to new contributors, as noted in our [Contributor Guide](https://github.com/centerofci/mathesar/blob/develop/CONTRIBUTING.md). Once we've already merged a PR of yours, then we'll be happy to assign tickets to you after that. The reason for this policy is that in the past it has been a maintenance burden for us to manage ticket assignments while having an overwhelming volume of people fail to submit their first PR when initially expressing intent to contribute.

**Comment by seancolsen** [comment]
@Tweniee from your screenshot you appear to be attempting to import the `all_types` table through Mathesar's web interface. That is unfortunately not possible. You'll need to first clone the [mathesar-data-playground](https://github.com/centerofci/mathesar-data-playground) repo, `cd` into it, and then load the `all_types` table via psql with the following command:

```
sudo docker exec -i mathesar_dev_db bash -c 'psql -U mathesar' < all_data_types/all_data_types.sql
```

In general, it would be better to ask these kind of questions in [Matrix](https://wiki.mathesar.org/en/community/matrix), just so that we can keep conversation within this page focused on the issue and the steps needed to fix it. Matrix is also better for troubleshooting things like this because it allows for faster back-and-forth. If you have any other trouble getting things set up, please find us in Matrix and we can help you there.

**Comment by Tweniee** [comment]
@seancolsen, it seems that the event it's listening for, `columnsFetched`, is not set anywhere in the code. I couldn't find it in the listener list as shown in the screenshot, and it's possible that it was accidentally removed by someone.

Since I'm new here and still getting familiar with the flow, I would appreciate your assistance. Could you provide guidance on how to address this issue or any other suggestions you may have?



![Screenshot from 2023-11-20 11-33-30](https://github.com/mathesar-foundation/mathesar/assets/93429474/6d135067-15ec-4e80-8a16-8cd27a026061)
![Screenshot from 2023-11-20 11-35-43](https://github.com/mathesar-foundation/mathesar/assets/93429474/dc3fa74f-0f0e-4323-a298-945ce06a565e)

**Comment by seancolsen** [comment]
@Tweniee

> Could you provide guidance on how to address this issue

Unfortunately, no. This issue is a bug that will require clever troubleshooting in order to diagnose the problem. It's not a good issue for a first-time contributor which is why it's not labeled "good first issue". I have a hunch that the fix will probably be pretty small, but identifying the fix is going to be tricky. If you have more questions, please ask in Matrix so that we avoid cluttering this thread. I suggest trying the "Mentoring Programs" room. Keep in mind though that the maintainers team generally has very limited capacity to help community contributors.

**Comment by shamblonaut** [comment]
@seancolsen Has this issue been resolved since? I could not reproduce the issue.

Might be related to https://github.com/mathesar-foundation/mathesar/issues/3826

https://github.com/user-attachments/assets/40ad0250-2d98-48a3-a793-69d27d93eea0

**Comment by seancolsen** [comment]
Cool. Yeah I can't reproduce this anymore either. Closing. Thanks @shamblonaut
